apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
  namespace: istio-system
spec:
  version: v1.1
  istio:
#    security:
#      selfSigned: false
    global:
      proxy:
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 64Mi
      mtls:
        enabled: false
    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
      istio-ingressgateway:
        autoscaleEnabled: false
        ior_enabled: false
        type: NodePort
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
    mixer:
      policy:
        autoscaleEnabled: false
      telemetry:
        autoscaleEnabled: false
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
    pilot:
      autoscaleEnabled: false
      traceSampling: 100
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
    kiali:
      enabled: true
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
    grafana:
      enabled: true
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
    tracing:
      enabled: true
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
      jaeger:
        template: all-in-one
  meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    accessLogFile: /dev/stdout
    accessLogFormat: ‘[%START_TIME%] %REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%%PROTOCOL% %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% %REQ(X-FORWARDED-FOR)% “%REQ(USER-AGENT)%” %REQ(X-REQUEST-ID)% “%REQ(:AUTHORITY)” UPSTREAM_HOST %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS%’
