apiVersion: v1
items:
- apiVersion: authentication.maistra.io/v1
  kind: ServiceMeshPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"authentication.maistra.io/v1","kind":"ServiceMeshPolicy","metadata":{"annotations":{"maistra.io/mesh-generation":"1.0.10-2.el8-1"},"labels":{"app":"security","app.kubernetes.io/component":"security","app.kubernetes.io/instance":"istio-system","app.kubernetes.io/managed-by":"maistra-istio-operator","app.kubernetes.io/name":"security","app.kubernetes.io/part-of":"istio","app.kubernetes.io/version":"1.0.10-2.el8-1","chart":"security","heritage":"Tiller","maistra-version":"1.0.10","maistra.io/owner":"istio-system","release":"istio"},"name":"default","namespace":"istio-system","ownerReferences":[{"apiVersion":"maistra.io/v1","blockOwnerDeletion":true,"controller":true,"kind":"ServiceMeshControlPlane","name":"basic-install","uid":"d300d440-2579-4d9e-a122-4d43fc5a1917"}]},"spec":{"peers":[{"mtls":{"mode":"PERMISSIVE"}}]}}
      maistra.io/mesh-generation: 1.0.10-2.el8-1
    creationTimestamp: "2020-04-05T14:10:46Z"
    generation: 1
    labels:
      app: security
      app.kubernetes.io/component: security
      app.kubernetes.io/instance: istio-system
      app.kubernetes.io/managed-by: maistra-istio-operator
      app.kubernetes.io/name: security
      app.kubernetes.io/part-of: istio
      app.kubernetes.io/version: 1.0.10-2.el8-1
      chart: security
      heritage: Tiller
      maistra-version: 1.0.10
      maistra.io/owner: istio-system
      release: istio
    name: default
    namespace: istio-system
    ownerReferences:
    - apiVersion: maistra.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: ServiceMeshControlPlane
      name: basic-install
      uid: d300d440-2579-4d9e-a122-4d43fc5a1917
    resourceVersion: "432973"
    selfLink: /apis/authentication.maistra.io/v1/namespaces/istio-system/servicemeshpolicies/default
    uid: 1c1cd8a8-b1fb-4ceb-a8b3-70aa8b2836e6
  spec:
    peers:
    - mtls:
        mode: PERMISSIVE
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
